window.experimental_default_hud_definition_json = {
  "elements": [
    {
      "t": "item_picked",
      "x": 8,
      "y": 2.5,
      "fontSize": "2.2",
      "shadow": 1,
      "icon": 1,
      "owner": "1",
      "pivot": "bottom-left",
      "iconWidth": 3.5,
      "gid": 6
    },
    {
      "t": "chat",
      "x": 4,
      "y": "75",
      "height": 30,
      "width": 50,
      "fontSize": "1.6",
      "align": "left",
      "color": "white",
      "pivot": "bottom-left"
    },
    {
      "t": "hp_bar",
      "x": 8,
      "y": 32.5,
      "width": 23,
      "height": 2.6,
      "color": "#2CD86B",
      "threshold": "100",
      "thresholdColor": "#2CD86B",
      "segments": "14",
      "bRadius": "0",
      "cCode": "15",
      "rightToLeft": 0,
      "pivot": "left-edge",
      "boxShadow": 1,
      "skewX": 0,
      "skewY": 0,
      "gid": 6
    },
    {
      "t": "armor_bar",
      "x": 8,
      "y": 67.5,
      "width": 23,
      "height": 2.6,
      "color": "#FFFFFF",
      "threshold": "100",
      "thresholdColor": "#FFFFFF",
      "segments": "14",
      "bRadius": "0",
      "cCode": "15",
      "rightToLeft": 0,
      "pivot": "left-edge",
      "boxShadow": 1,
      "skewX": 0,
      "skewY": 0,
      "gid": 6
    },
    {
      "t": "hp",
      "x": 59,
      "y": 32.5,
      "width": 9.5,
      "fontSize": "3.3",
      "scaleOnPickup": "1",
      "color": "#2CD86B",
      "threshold": "100",
      "thresholdColor": "#2CD86B",
      "shadow": 1,
      "pivot": "right-edge",
      "gid": 6,
      "font": "montserrat"
    },
    {
      "t": "armor",
      "x": 59,
      "y": 67.5,
      "width": 9.5,
      "fontSize": "3.3",
      "scaleOnPickup": "1",
      "color": "#FFFFFF",
      "threshold": "100",
      "thresholdColor": "#FFFFFF",
      "shadow": 1,
      "pivot": "right-edge",
      "hideIf0": "0",
      "gid": 6,
      "font": "montserrat"
    },
    {
      "t": "you_fragged",
      "x": 50,
      "y": 68,
      "fontSize": "3",
      "font": "veneer-italic",
      "color": "white",
      "pivot": "bottom-edge",
      "align": "center"
    },
    {
      "t": "my_team_score",
      "x": 30,
      "y": "10",
      "sWidth": "7",
      "nWidth": "20",
      "height": 4.5,
      "align": "center",
      "fontSize": "2.6",
      "reverse": 1,
      "players": 1,
      "pivot": "top-right",
      "name_bg_opacity": "BF",
      "gid": 5,
      "sC": "#FFFFFF",
      "color": "#FFFFFF",
      "sFont": "furore",
      "font": "montserrat",
      "shadow": 1
    },
    {
      "t": "enemy_team_score",
      "x": 70,
      "y": "10",
      "sWidth": "7",
      "nWidth": "20",
      "height": 4.5,
      "align": "center",
      "fontSize": "2.6",
      "reverse": "0",
      "players": "1",
      "pivot": "top-left",
      "name_bg_opacity": "BF",
      "gid": 5,
      "sC": "#FFFFFF",
      "color": "#FFFFFF",
      "sFont": "furore",
      "font": "montserrat",
      "shadow": 1
    },
    {
      "t": "teammates_alive",
      "x": 22.8,
      "y": 77.5,
      "fontSize": "1.5",
      "color": "#2CD86B",
      "align": "center",
      "shadow": 1,
      "aliveText": "1",
      "teamColor": "1",
      "pivot": "top-edge",
      "gid": 5,
      "font": "roboto-bold"
    },
    {
      "t": "enemies_alive",
      "x": 76.4,
      "y": 77.5,
      "fontSize": "1.5",
      "color": "#c80f0f",
      "align": "center",
      "shadow": "1",
      "aliveText": "1",
      "pivot": "top-edge",
      "teamColor": "1",
      "gid": 5,
      "font": "roboto-bold"
    },
    {
      "t": "frag_feed",
      "x": 96,
      "y": 3,
      "height": 20,
      "width": 30,
      "fontSize": "2.2",
      "v_align": "flex-end",
      "bottomUp": "0",
      "direction": "bottom",
      "pivot": "top-right",
      "font": "roboto-bold"
    },
    {
      "t": "game_timer",
      "x": 50,
      "y": "3.5",
      "fontSize": "4.5",
      "shadow": "1",
      "color": "rgba(255,255,255,0.99)",
      "gid": 5,
      "pivot": "top-edge",
      "font": "roboto-bold"
    },
    {
      "t": "time_limit",
      "x": 50,
      "y": 71.25,
      "fontSize": "1.5",
      "shadow": "1",
      "pivot": "top-edge",
      "align": "center",
      "gid": 5
    },
    {
      "t": "dodge",
      "x": 50,
      "y": 61,
      "fontSize": "1.5",
      "iSize": "5",
      "mC": "#FFFFFF",
      "icon_inactive_opacity": "0.2",
      "bRadius": "0.8",
      "cCode": "15",
      "bWidth": "0",
      "bgC": "#00000000",
      "aT": 2,
      "pivot": "center"
    },
    {
      "t": "item",
      "x": 50,
      "y": 90,
      "fontSize": "1",
      "iSize": "10",
      "mC": "#FFFFFFC2",
      "bRadius": "10",
      "cCode": "15",
      "bWidth": "3",
      "bgC": "#00000063",
      "pivot": "center",
      "style": "default",
      "iC": "custom",
      "font": "roboto-bold"
    },
    {
      "t": "weapons_list",
      "gid": -1,
      "x": 96,
      "y": 77,
      "mode": "all",
      "direction": "vertical reverse",
      "wDirection": "horizontal",
      "font": "montserrat",
      "fontSize": "2",
      "aWidth": "5.5",
      "aPadding": "0",
      "aAlign": "center",
      "accShow": 0,
      "accFontSize": "1",
      "iHeight": "35",
      "iWidth": "48",
      "wSepWidth": "1",
      "sepWidth": "24",
      "cBitWidth": "0",
      "keybindShow": 1,
      "aKeybindShow": "0",
      "aBarShow": 0,
      "aBarWidth": "0.6",
      "aBarWC": 0,
      "iOpacityInactive": "1",
      "aOpacityInactive": "1",
      "iC": "custom",
      "iCCustom": "#FFFFFFCC",
      "iCActive": "weapon",
      "iCActiveCustom": "#FFFFFF",
      "iBGC": "custom",
      "iBGCCustom": "#0000003D",
      "iBGCActive": "custom",
      "iBGCActiveCustom": "#00000094",
      "aC": "custom",
      "aCCustom": "#FFFFFFBF",
      "aCActive": "custom",
      "aCActiveCustom": "#FFFFFF",
      "aBGC": "custom",
      "aBGCCustom": "#00000012",
      "aBGCActive": "weapon",
      "aBGCActiveCustom": "#00000000",
      "pivot": "bottom-right"
    },
    {
      "t": "powerup",
      "gid": 6,
      "x": 72,
      "y": 50,
      "fontSize": "1.5",
      "iSize": "7",
      "mC": "white",
      "bRadius": "10",
      "cCode": "15",
      "bWidth": 0.2,
      "bgC": "#24232188",
      "iC": "custom",
      "iCCustom": "#ffffff",
      "style": "default",
      "pivot": "center",
      "font": "roboto-bold"
    },
    {
      "t": "rect",
      "gid": 4,
      "pivot": "left-edge",
      "x": 57,
      "y": "50",
      "width": 0.1,
      "height": 5,
      "bRadius": "0",
      "cCode": "15",
      "skewX": "0",
      "skewY": "0",
      "bgC": "custom",
      "bgCCustom": "#FFFFFF",
      "hide_dead": "1",
      "advanced": ""
    },
    {
      "t": "current_weapon_icon",
      "gid": 4,
      "x": 100,
      "y": "50",
      "width": 5,
      "height": 5,
      "weapon_fill": 0,
      "fill": "white",
      "pivot": "right-edge",
      "shadow": 1
    },
    {
      "t": "current_ammo",
      "gid": 4,
      "x": 42,
      "y": "50",
      "fontSize": "5",
      "align": "center",
      "color": "#FFFFFF",
      "font": "montserrat",
      "shadow": 1,
      "weapon_fill": 0,
      "pivot": "right-edge"
    },
    {
      "t": "fps",
      "gid": -1,
      "x": 0,
      "y": 0,
      "fontSize": "1.5",
      "font": "roboto",
      "pivot": "top-left",
      "shadow": 1
    },
    {
      "t": "icon",
      "gid": 6,
      "x": 64,
      "y": 32.5,
      "width": 2.4,
      "height": 2.4,
      "stroke": "#00000000",
      "stroke_width": "15",
      "fill": "#2CD86B",
      "icon": "hp",
      "shadow": "1",
      "hide_dead": "1",
      "iconShadow": 1,
      "pivot": "right-edge"
    },
    {
      "t": "icon",
      "gid": 6,
      "x": 64,
      "y": 67.5,
      "width": 2.4,
      "height": 2.4,
      "stroke": "#00000000",
      "stroke_width": "15",
      "fill": "#FFFFFF",
      "icon": "armor",
      "shadow": "1",
      "hide_dead": "1",
      "pivot": "right-edge",
      "iconShadow": 1
    },
    {
      "t": "voicechat",
      "gid": -1,
      "x": 4,
      "y": 3,
      "fontSize": "1.5",
      "font": "montserrat",
      "color": "white",
      "pivot": "top-left",
      "v_align": "flex-start",
      "iC": "#00ff00"
    },
    {
      "t": "coins",
      "gid": -1,
      "x": 50,
      "y": 20,
      "fontSize": "4",
      "color": "#ffffff",
      "scaleOnPickup": "1",
      "advanced": "",
      "font": "montserrat-bold"
    },
    {
      "t": "g_meter",
      "gid": -1,
      "x": "50",
      "y": "78",
      "pivot": "center",
      "fontSize": "4.5",
      "font": "roboto-bold",
      "ringInnerSize": "78",
      "size": "14",
      "opacity": "0.6",
      "showSpeed": "2",
      "cjspeed": "390",
      "previewpitch": "-23.5"
    }
  ],
  "groups": [
    {
      "gid": 4,
      "x": "96",
      "y": "95",
      "width": 18,
      "height": 10,
      "pivot": "bottom-right",
      "advanced": ""
    },
    {
      "gid": 5,
      "x": 50,
      "y": "2",
      "width": 50,
      "height": 8,
      "pivot": "top-edge",
      "advanced": ""
    },
    {
      "gid": 6,
      "x": "4",
      "y": "95",
      "width": 60,
      "height": 10,
      "pivot": "bottom-left",
      "advanced": ""
    }
  ]
};