! function(e, a) {
    e.ReactIntlLocaleData = e.ReactIntlLocaleData || {}, e.ReactIntlLocaleData.en = a()
}(this, function() {
    "use strict";
    return [{
        locale: "en",
        pluralRuleFunction: function(e, a) {
            var n = String(e).split("."),
                l = !n[1],
                o = Number(n[0]) == e,
                t = o && n[0].slice(-1),
                r = o && n[0].slice(-2);
            return a ? 1 == t && 11 != r ? "one" : 2 == t && 12 != r ? "two" : 3 == t && 13 != r ? "few" : "other" : 1 == e && l ? "one" : "other"
        },
    }, {
        locale: "en_001",
        parentLocale: "en"
    }, {
        locale: "en_150",
        parentLocale: "en_001"
    }, {
        locale: "en_AG",
        parentLocale: "en_001"
    }, {
        locale: "en_AI",
        parentLocale: "en_001"
    }, {
        locale: "en_AS",
        parentLocale: "en"
    }, {
        locale: "en_AT",
        parentLocale: "en_150"
    }, {
        locale: "en_AU",
        parentLocale: "en_001"
    }, {
        locale: "en_BB",
        parentLocale: "en_001"
    }, {
        locale: "en_BE",
        parentLocale: "en_001"
    }, {
        locale: "en_BI",
        parentLocale: "en"
    }, {
        locale: "en_BM",
        parentLocale: "en_001"
    }, {
        locale: "en_BS",
        parentLocale: "en_001"
    }, {
        locale: "en_BW",
        parentLocale: "en_001"
    }, {
        locale: "en_BZ",
        parentLocale: "en_001"
    }, {
        locale: "en_CA",
        parentLocale: "en_001"
    }, {
        locale: "en_CC",
        parentLocale: "en_001"
    }, {
        locale: "en_CH",
        parentLocale: "en_150"
    }, {
        locale: "en_CK",
        parentLocale: "en_001"
    }, {
        locale: "en_CM",
        parentLocale: "en_001"
    }, {
        locale: "en_CX",
        parentLocale: "en_001"
    }, {
        locale: "en_CY",
        parentLocale: "en_001"
    }, {
        locale: "en_DE",
        parentLocale: "en_150"
    }, {
        locale: "en_DG",
        parentLocale: "en_001"
    }, {
        locale: "en_DK",
        parentLocale: "en_150"
    }, {
        locale: "en_DM",
        parentLocale: "en_001"
    }, {
        locale: "en_Dsrt",
        pluralRuleFunction: function(e, a) {
            return "other"
        },
    }, {
        locale: "en_ER",
        parentLocale: "en_001"
    }, {
        locale: "en_FI",
        parentLocale: "en_150"
    }, {
        locale: "en_FJ",
        parentLocale: "en_001"
    }, {
        locale: "en_FK",
        parentLocale: "en_001"
    }, {
        locale: "en_FM",
        parentLocale: "en_001"
    }, {
        locale: "en_GB",
        parentLocale: "en_001"
    }, {
        locale: "en_GD",
        parentLocale: "en_001"
    }, {
        locale: "en_GG",
        parentLocale: "en_001"
    }, {
        locale: "en_GH",
        parentLocale: "en_001"
    }, {
        locale: "en_GI",
        parentLocale: "en_001"
    }, {
        locale: "en_GM",
        parentLocale: "en_001"
    }, {
        locale: "en_GU",
        parentLocale: "en"
    }, {
        locale: "en_GY",
        parentLocale: "en_001"
    }, {
        locale: "en_HK",
        parentLocale: "en_001"
    }, {
        locale: "en_IE",
        parentLocale: "en_001"
    }, {
        locale: "en_IL",
        parentLocale: "en_001"
    }, {
        locale: "en_IM",
        parentLocale: "en_001"
    }, {
        locale: "en_IN",
        parentLocale: "en_001"
    }, {
        locale: "en_IO",
        parentLocale: "en_001"
    }, {
        locale: "en_JE",
        parentLocale: "en_001"
    }, {
        locale: "en_JM",
        parentLocale: "en_001"
    }, {
        locale: "en_KE",
        parentLocale: "en_001"
    }, {
        locale: "en_KI",
        parentLocale: "en_001"
    }, {
        locale: "en_KN",
        parentLocale: "en_001"
    }, {
        locale: "en_KY",
        parentLocale: "en_001"
    }, {
        locale: "en_LC",
        parentLocale: "en_001"
    }, {
        locale: "en_LR",
        parentLocale: "en_001"
    }, {
        locale: "en_LS",
        parentLocale: "en_001"
    }, {
        locale: "en_MG",
        parentLocale: "en_001"
    }, {
        locale: "en_MH",
        parentLocale: "en"
    }, {
        locale: "en_MO",
        parentLocale: "en_001"
    }, {
        locale: "en_MP",
        parentLocale: "en"
    }, {
        locale: "en_MS",
        parentLocale: "en_001"
    }, {
        locale: "en_MT",
        parentLocale: "en_001"
    }, {
        locale: "en_MU",
        parentLocale: "en_001"
    }, {
        locale: "en_MW",
        parentLocale: "en_001"
    }, {
        locale: "en_MY",
        parentLocale: "en_001"
    }, {
        locale: "en_NA",
        parentLocale: "en_001"
    }, {
        locale: "en_NF",
        parentLocale: "en_001"
    }, {
        locale: "en_NG",
        parentLocale: "en_001"
    }, {
        locale: "en_NL",
        parentLocale: "en_150"
    }, {
        locale: "en_NR",
        parentLocale: "en_001"
    }, {
        locale: "en_NU",
        parentLocale: "en_001"
    }, {
        locale: "en_NZ",
        parentLocale: "en_001"
    }, {
        locale: "en_PG",
        parentLocale: "en_001"
    }, {
        locale: "en_PH",
        parentLocale: "en_001"
    }, {
        locale: "en_PK",
        parentLocale: "en_001"
    }, {
        locale: "en_PN",
        parentLocale: "en_001"
    }, {
        locale: "en_PR",
        parentLocale: "en"
    }, {
        locale: "en_PW",
        parentLocale: "en_001"
    }, {
        locale: "en_RW",
        parentLocale: "en_001"
    }, {
        locale: "en_SB",
        parentLocale: "en_001"
    }, {
        locale: "en_SC",
        parentLocale: "en_001"
    }, {
        locale: "en_SD",
        parentLocale: "en_001"
    }, {
        locale: "en_SE",
        parentLocale: "en_150"
    }, {
        locale: "en_SG",
        parentLocale: "en_001"
    }, {
        locale: "en_SH",
        parentLocale: "en_001"
    }, {
        locale: "en_SI",
        parentLocale: "en_150"
    }, {
        locale: "en_SL",
        parentLocale: "en_001"
    }, {
        locale: "en_SS",
        parentLocale: "en_001"
    }, {
        locale: "en_SX",
        parentLocale: "en_001"
    }, {
        locale: "en_SZ",
        parentLocale: "en_001"
    }, {
        locale: "en_Shaw",
        pluralRuleFunction: function(e, a) {
            return "other"
        },
    }, {
        locale: "en_TC",
        parentLocale: "en_001"
    }, {
        locale: "en_TK",
        parentLocale: "en_001"
    }, {
        locale: "en_TO",
        parentLocale: "en_001"
    }, {
        locale: "en_TT",
        parentLocale: "en_001"
    }, {
        locale: "en_TV",
        parentLocale: "en_001"
    }, {
        locale: "en_TZ",
        parentLocale: "en_001"
    }, {
        locale: "en_UG",
        parentLocale: "en_001"
    }, {
        locale: "en_UM",
        parentLocale: "en"
    }, {
        locale: "en_US",
        parentLocale: "en"
    }, {
        locale: "en_VC",
        parentLocale: "en_001"
    }, {
        locale: "en_VG",
        parentLocale: "en_001"
    }, {
        locale: "en_VI",
        parentLocale: "en"
    }, {
        locale: "en_VU",
        parentLocale: "en_001"
    }, {
        locale: "en_WS",
        parentLocale: "en_001"
    }, {
        locale: "en_ZA",
        parentLocale: "en_001"
    }, {
        locale: "en_ZM",
        parentLocale: "en_001"
    }, {
        locale: "en_ZW",
        parentLocale: "en_001"
    }]
});