! function(e, a) {
    e.ReactIntlLocaleData = e.ReactIntlLocaleData || {}, e.ReactIntlLocaleData.es = a()
}(this, function() {
    "use strict";
    return [{
        locale: "es",
        pluralRuleFunction: function(e, a) {
            return a ? "other" : 1 == e ? "one" : "other"
        },
    }, {
        locale: "es_419",
        parentLocale: "es"
    }, {
        locale: "es_AR",
        parentLocale: "es_419"
    }, {
        locale: "es_BO",
        parentLocale: "es_419"
    }, {
        locale: "es_BR",
        parentLocale: "es_419"
    }, {
        locale: "es_BZ",
        parentLocale: "es_419"
    }, {
        locale: "es_CL",
        parentLocale: "es_419"
    }, {
        locale: "es_CO",
        parentLocale: "es_419"
    }, {
        locale: "es_CR",
        parentLocale: "es_419",
    }, {
        locale: "es_CU",
        parentLocale: "es_419"
    }, {
        locale: "es_DO",
        parentLocale: "es_419",
    }, {
        locale: "es_EA",
        parentLocale: "es"
    }, {
        locale: "es_EC",
        parentLocale: "es_419"
    }, {
        locale: "es_GQ",
        parentLocale: "es"
    }, {
        locale: "es_GT",
        parentLocale: "es_419",
    }, {
        locale: "es_HN",
        parentLocale: "es_419",
    }, {
        locale: "es_IC",
        parentLocale: "es"
    }, {
        locale: "es_MX",
        parentLocale: "es_419",
    }, {
        locale: "es_NI",
        parentLocale: "es_419",
    }, {
        locale: "es_PA",
        parentLocale: "es_419",
    }, {
        locale: "es_PE",
        parentLocale: "es_419"
    }, {
        locale: "es_PH",
        parentLocale: "es"
    }, {
        locale: "es_PR",
        parentLocale: "es_419"
    }, {
        locale: "es_PY",
        parentLocale: "es_419",
    }, {
        locale: "es_SV",
        parentLocale: "es_419",
    }, {
        locale: "es_US",
        parentLocale: "es_419"
    }, {
        locale: "es_UY",
        parentLocale: "es_419"
    }, {
        locale: "es_VE",
        parentLocale: "es_419"
    }]
});