! function(e, a) {
    e.ReactIntlLocaleData = e.ReactIntlLocaleData || {}, e.ReactIntlLocaleData.fr = a()
}(this, function() {
    "use strict";
    return [{
        locale: "fr",
        pluralRuleFunction: function(e, a) {
            return a ? 1 == e ? "one" : "other" : e >= 0 && e < 2 ? "one" : "other"
        },
    }, {
        locale: "fr_BE",
        parentLocale: "fr"
    }, {
        locale: "fr_BF",
        parentLocale: "fr"
    }, {
        locale: "fr_BI",
        parentLocale: "fr"
    }, {
        locale: "fr_BJ",
        parentLocale: "fr"
    }, {
        locale: "fr_BL",
        parentLocale: "fr"
    }, {
        locale: "fr_CA",
        parentLocale: "fr",
    }, {
        locale: "fr_CD",
        parentLocale: "fr"
    }, {
        locale: "fr_CF",
        parentLocale: "fr"
    }, {
        locale: "fr_CG",
        parentLocale: "fr"
    }, {
        locale: "fr_CH",
        parentLocale: "fr"
    }, {
        locale: "fr_CI",
        parentLocale: "fr"
    }, {
        locale: "fr_CM",
        parentLocale: "fr"
    }, {
        locale: "fr_DJ",
        parentLocale: "fr"
    }, {
        locale: "fr_DZ",
        parentLocale: "fr"
    }, {
        locale: "fr_GA",
        parentLocale: "fr"
    }, {
        locale: "fr_GF",
        parentLocale: "fr"
    }, {
        locale: "fr_GN",
        parentLocale: "fr"
    }, {
        locale: "fr_GP",
        parentLocale: "fr"
    }, {
        locale: "fr_GQ",
        parentLocale: "fr"
    }, {
        locale: "fr_HT",
        parentLocale: "fr"
    }, {
        locale: "fr_KM",
        parentLocale: "fr"
    }, {
        locale: "fr_LU",
        parentLocale: "fr"
    }, {
        locale: "fr_MA",
        parentLocale: "fr"
    }, {
        locale: "fr_MC",
        parentLocale: "fr"
    }, {
        locale: "fr_MF",
        parentLocale: "fr"
    }, {
        locale: "fr_MG",
        parentLocale: "fr"
    }, {
        locale: "fr_ML",
        parentLocale: "fr"
    }, {
        locale: "fr_MQ",
        parentLocale: "fr"
    }, {
        locale: "fr_MR",
        parentLocale: "fr"
    }, {
        locale: "fr_MU",
        parentLocale: "fr"
    }, {
        locale: "fr_NC",
        parentLocale: "fr"
    }, {
        locale: "fr_NE",
        parentLocale: "fr"
    }, {
        locale: "fr_PF",
        parentLocale: "fr"
    }, {
        locale: "fr_PM",
        parentLocale: "fr"
    }, {
        locale: "fr_RE",
        parentLocale: "fr"
    }, {
        locale: "fr_RW",
        parentLocale: "fr"
    }, {
        locale: "fr_SC",
        parentLocale: "fr"
    }, {
        locale: "fr_SN",
        parentLocale: "fr"
    }, {
        locale: "fr_SY",
        parentLocale: "fr"
    }, {
        locale: "fr_TD",
        parentLocale: "fr"
    }, {
        locale: "fr_TG",
        parentLocale: "fr"
    }, {
        locale: "fr_TN",
        parentLocale: "fr"
    }, {
        locale: "fr_VU",
        parentLocale: "fr"
    }, {
        locale: "fr_WF",
        parentLocale: "fr"
    }, {
        locale: "fr_YT",
        parentLocale: "fr"
    }]
});